Page({
  data:{
    thisWeekMovie:{
        name:"教父",
        comment:"最精彩的剧本,最真实的黑帮电影.",
        imagePath:"/images/jf.jpg",
        isHighlyRecommended:false
    },
    count:123,
    score:61
  }
})